// ===== 博客文章数据 =====
const POSTS = [
  {
    id: 1,
    title: "2025 年前端开发工具链选型指南",
    excerpt: "从构建工具、包管理器到测试框架，全面梳理现代前端工程化体系，帮你在眼花缭乱的选项中找到最适合自己的组合。",
    category: "技术",
    catClass: "cat-tech",
    emoji: "⚙️",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年12月20日",
    readTime: 10,
    views: 7105
  },
  {
    id: 2,
    title: "极简主义生活方式的 30 天实践",
    excerpt: "我尝试了一个月的极简主义生活，清理了家里三分之一的物品，发现了更多时间和内心的宁静。",
    category: "生活",
    catClass: "cat-life",
    emoji: "🌿",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年11月18日",
    readTime: 6,
    views: 5893
  },
  {
    id: 3,
    title: "日本京都深度游攻略：六天五晚全记录",
    excerpt: "不走马观花，不跟团打卡，用六天时间沉浸感受这座千年古都的美食、寺庙与街巷。",
    category: "旅行",
    catClass: "cat-travel",
    emoji: "⛩️",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年11月5日",
    readTime: 12,
    views: 4670
  },
  {
    id: 4,
    title: "Figma 高效工作流：从想法到交付",
    excerpt: "分享我在日常设计工作中积累的 Figma 技巧和工作流程，让设计与开发的协作更加顺畅高效。",
    category: "设计",
    catClass: "cat-design",
    emoji: "🎨",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年10月20日",
    readTime: 8,
    views: 3958
  },
  {
    id: 5,
    title: "用 Vue 3 Composition API 重构一个复杂组件",
    excerpt: "以一个实际项目中的复杂表单组件为例，演示如何用 Composition API 将混乱的 Options API 代码重构为清晰可维护的模块。",
    category: "技术",
    catClass: "cat-tech",
    emoji: "💚",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年10月8日",
    readTime: 14,
    views: 3420
  },
  {
    id: 6,
    title: "深夜厨房：一个程序员的家常菜修炼之路",
    excerpt: "从只会煮泡面，到能做出一桌像样的饭菜，分享两年自学推敲的心得和几道必会家常菜谱。",
    category: "美食",
    catClass: "cat-food",
    emoji: "🍜",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年10月1日",
    readTime: 7,
    views: 2891
  },
  {
    id: 7,
    title: "TypeScript 5.x 新特性全解析",
    excerpt: "详细介绍 TypeScript 5.x 中引入的装饰器、const 类型参数等重磅特性，附带真实代码示例。",
    category: "技术",
    catClass: "cat-tech",
    emoji: "💙",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年9月20日",
    readTime: 11,
    views: 2634
  },
  {
    id: 8,
    title: "设计系统从零到一：落地实践总结",
    excerpt: "回顾在工作中主导建立公司设计系统的全过程，从组件规范、设计 Token 到文档建设的完整经验分享。",
    category: "设计",
    catClass: "cat-design",
    emoji: "🏗️",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年9月1日",
    readTime: 15,
    views: 2210
  },
  {
    id: 9,
    title: "云南大理慢活半月：返璞归真的旅途",
    excerpt: "在大理的 15 天，住在洱海边的民宿，骑车环湖，吃路边烧烤，这是治愈疲惫最好的方式。",
    category: "旅行",
    catClass: "cat-travel",
    emoji: "🏕️",
    gradient: "var(--primary)",
    author: "晨曦",
    date: "2025年8月22日",
    readTime: 9,
    views: 1987
  }
];
